[shell]
program='/bin/bash'
args=['--login']
[env]
TERM="xterm-256color"
[colors.primary]
background='0x262626'
foreground='0xeaeaea'
[colors.bright]
black='0x666666'
blue='0x7aa6da'
cyan='0x54ced6'
green='0x9ec400'
magenta='0xb77ee0'
red='0xff3334'
white='0xffffff'
yellow='0xe7c547'
[colors.normal]
black='0x000000'
blue='0x7aa6da'
cyan='0x70c0ba'
green='0xb9ca4a'
magenta='0xc397d8'
red='0xd54e53'
white='0xeaeaea'
yellow='0xe6c547'
[window]
dimensions={columns=0, lines=0}
dynamic_title=true
[font]
size=16
normal.family='FiraMono Nerd Font'
bold.family='FiraMono Nerd Font'
